# General setup
# -------------
dist: trusty
sudo: required
language: python
python:
    - "2.7"
# Allows the python virtualenv to use apt-get installed packages, which
# is essential (as ROS recommends this and pip doesn't seem to contain
# all packages, or contains them with errors).
virtualenv:
    system_site_packages: true
# Allow caching of debian (apt-get) packages. This means they're cached
# on Travis, so we still have to download/install them, but it will be
# faster than going to the ubuntu repositories.
cache: apt
# Before anything, see if we can get the mongoDB troubles out of the way.
# Note that this is a Travis-CI specific problem; this is not needed in
# general.
before_install: # Use this to prepare the system to install prerequisites or dependencies
    # Define some config vars
    - sudo apt-get --purge remove mongodb-10gen postgresql-9.2 postgresql-contrib-9.2 postgresql-9.3 postgresql-contrib-9.3
    - export ROS_DISTRO=indigo
    # Settings to make installing script more general.
    - export ROS_CI_DESKTOP=`lsb_release -cs`  # e.g. 'precise'

notifications:
  email: false

# Commands to install dependencies
# --------------------------------
before_install:
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'
    - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
    - sudo apt-get update -qq
    - sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin
    - source /opt/ros/$ROS_DISTRO/setup.bash
    # Prepare rosdep to install dependencies.
    - sudo rosdep init
    - rosdep update
    # Create workspace.
    - mkdir -p ~/catkin_ws/src
    - cd ..; mv final_package ~/catkin_ws/src
    - cd ~/catkin_ws/src
    - catkin_init_workspace
    # Install dependencies
    - cd ~/catkin_ws/
    - rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
    # Build
    - catkin_make

# Command to run tests
# --------------------
script:
    - catkin_make run_tests # Run tests using catkin
    - pep8 src/*.py test/*.py # Linter